### PR TITLE
add Delete and Find RequestFactories. Also did some refactoring of LightblueRequestFactory

### PR DESCRIPTION
**Pull request by dcrissman**
Add missing RequestFactories.

### CODE REVIEW

**Comment by dcrissman** [comment]
@paterczm Would you please review when you have a change? I think I will need this for the mediator.

**Comment by paterczm** [comment]
Could you explain the need for those factories? Most of the code is to pass data needed to create lightblue requests. That's boilerplate code imho.

**Comment by dcrissman** [comment]
Because routes are declared statically, performing dynamic CRUD operations on lightblue becomes difficult. These factory classes allow the route to specify header values that can be dynamically changed that can be used to build request instances.

**Comment by paterczm** [comment]
Can't we use a map of predefined lightblue requests? You could then use a header or endpoint uri parameter to pick the one you want to use by it's name. 

Even if we need the flexibility of building pretty much any lightblue request using string headers (which I doubt, but maybe you have some good examples), then I'm still concerned with this solution, as it introduces a number of thin wrappers over lightblue requests which add very little logic, but still need to be understood, maintained, unit tests created, etc.

**Comment by dcrissman** [comment]
For static requests that we know in advance, sure we could predefine them. But we cannot do that for requests where we don't have all the information up front. If we want to dynamically build requests (which I don't think is an unreasonable requirement), then camel needs a utility to build them at the route's runtime. So some sort of Bean or Processor is needed, and to me it makes sense to make these generic and reusable.

I am open to suggestions for improvements, but I hold that utilities like these are needed.

**Comment by paterczm** [comment]
You can always intercept a lightblue request in a bean or processor and alter it to your liking (or even create a new one from scratch). Perhaps a real life example would help me understand why utilities like that are needed.

**Comment by paterczm** [comment]
Are you thinking about the consumer (beginning of route, where you can't intercept anything)?

**Comment by dcrissman** [comment]
No,  more the LightblueProducer. It expects that the incoming body is a LightblueRequest. 

Maybe the better use case is an insert or update operation, where you have somehow generated data that needs to be added to the request. Not a factory on this PR, but as an example the LightblueInsertRequestFactory is a Processor that will do that for you. Reading and translating the In Body was fairly simple, the problem came in when the destination entity is not a guarantee. Say the insert could be for variable entities and versions. The easiest way I found to pass variables like entityName and entityVersion around is in the Route's header. So that is why the factories read from the headers if they were not already set. Essentially I am allowing the factories to be used either way, set the data directly, or use the headers to dynamically pass the variables around.

This PR was really just to round out supporting all the operation types.

**Comment by paterczm** [comment]
But why set things in the header when you can create (or alter existing) lightblue request?

**Comment by dcrissman** [comment]
Maybe I am wrong, but it looked to me like headers were the way to pass variables around on the Route.

**Comment by dcrissman** [comment]
I guess there are Properties also available on the Route. I don't know which is better, but they look similar.

**Comment by dcrissman** [comment]
It seems to me that camel is about small steps that when put together create a route, as opposed to a few monolithic Bean(s)/Processor(s). I see these factories as a way to, in the route, create the requests that can then be passed into the Producer.

**Comment by paterczm** [comment]
You can modify a lightblue request in small steps as well. Using headers (or properties) is storing lightblue request information in a map of key value pairs to be later converted to lightblue request. I don't see a point for this abstraction. Those headers/properties will already be specific to lightblue, so using lightblue-client model feels natural.

**Comment by dcrissman** [comment]
Maybe an example would be useful?

**Comment by dcrissman** [comment]
Discussions on this issue I am sure will continue, but in the meantime I prefer the changes in #28, so closing this issue in favour of that one.

**Pull request closed without merging**
